name: Build Qt 6.7

on:
  workflow_dispatch:

env:
  qt_version: 6.7.3
  openssl_version: 3.4.0

jobs:
  Build_x86:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Download Qt ${{ env.qt_version }} sources
        run: .\download_sources.cmd no_repack ${{ env.qt_version }} ${{ env.openssl_version }}

      - name: Install Qt jom
        run: .\install_jom.cmd

      - name: Build Qt ${{ env.qt_version }} x86
        run: .\build_sources.cmd Win32 ${{ env.qt_version }}

      - name: Upload built Qt
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Qt ${{ env.qt_version }} x86
          path: |
            archive/*
          compression-level: 0

      - name: Upload built OpenSSL ${{ env.openssl_version }}
        uses: actions/upload-artifact@v4.4.3
        with:
          name: OpenSSL ${{ env.qt_version }} x86
          path: |
            openssl-win32/bin/*.dll
            openssl-win32/bin/*.exe
            openssl-win32/bin/*.pdb
          compression-level: 9
